version: '3.8'
services:
  # MAP RELATED CONTAINERS
  postgis:
    image: docker.io/postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
  offline-map-data-loader:
    image: ghcr.io/tiiuae/tii-offline-map-data-loader:dubai
    depends_on:
      - postgis
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=postgis
      - NO_EXIT=true
  tegola-server:
    image: ghcr.io/tiiuae/tii-tegola-server:1.0.0
    restart: always
    depends_on:
      - postgis
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=postgis
  offline-map-server:
    image: ghcr.io/tiiuae/tii-offline-map-server:1.0.0
    restart: always
    depends_on:
      - tegola-server
    environment:
      - MAP_SERVER=http://tegola-server:8080
      - MAPTILER_API_KEY=F3MvahZzQR4MyTWDqyBH
    ports:
      - 8888:8888

  # NATS SERVER CONTAINERS
  management-nats:
    image: ghcr.io/tiiuae/drone-nats-server:1.0.0-swarm
    network_mode: host
    restart: always
    environment:
      - DRONE_DEVICE_ID={{device-id}}
      - MDNS_SERVICE=_swarm._tcp
      - MDNS_IP_ADDRESS={{ip-address}}
      - MDNS_INSTANCE={{device-id}}
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /var/lib/fogdata/certs/leaf.conf:/etc/nats/server.conf
      - /var/lib/fogdata/certs:/certs

  swarm-nats:
    image: ghcr.io/tiiuae/drone-nats-server:1.0.0-swarm
    container_name: swarm-nats
    restart: always
    environment:
      - DRONE_DEVICE_ID={{device-id}}
    ports:
      - 4223:4222
      - 4290:4280
      - 7222:7422

  # SWARM MANAGEMENT CONTAINERS
  swarm-server:
    image: ghcr.io/tiiuae/tii-swarm-server:1.0.1
    network_mode: host
    restart: always
    environment:
      - DRONE_DEVICE_ID={{device-id}}
      # - SWARM_SERVER_PORT=4222
      - SWARM_SERVER_KEY_SOURCE=filesystem
      - SWARM_SERVER_FLEET_CERTIFICATE_PATH=/certs/identity.crt
      - SWARM_SERVER_FLEET_KEY_PATH=/certs/identity.key
      - SWARM_SERVER_SWARM_CA_CERTIFICATE_PATH=/certs/swarm.crt
      - SWARM_SERVER_SWARM_KEY_PATH=/certs/swarm.key
      - SWARM_SERVER_SWARM_SERVER_CERTIFICATE_PATH=/certs/swarm_server.crt # Autogenerated by swarm server
      - SWARM_SERVER_SWARM_SERVER_KEY_PATH=/certs/swarm_server.key         # Autogenerated by swarm server
      - SWARM_SERVER_ROOT_CERTIFICATE_PATH=/certs/fleet_ca.crt
      - SWARM_SERVER_HOSTNAME={{ip-address}}
      - SWARM_SERVER_HOST_IP={{ip-address}}
      # - SWARM_SERVER_KEY_PATH=/certs/intermediate/private.pem
      - SWARM_SERVER_OPTIONS_FLEET_NATS_URL=nats://localhost:4222
      - SWARM_SERVER_OPTIONS_SWARM_NATS_INTERNAL_CLIENT_URL=nats://localhost:4223
      - SWARM_SERVER_OPTIONS_SWARM_NATS_EXTERNAL_CLIENT_URL=nats://{{ip-address}}:4223
      - SWARM_SERVER_OPTIONS_SWARM_NATS_EXTERNAL_LEAF_URL=nats://{{ip-address}}:7222
      - SWARM_SERVER_OPTIONS_SWARM_NATS_EXTERNAL_WS_URL=nats://{{ip-address}}:4280
      - SWARM_SERVER_TLS_ENABLED=true
    volumes:
      - /var/lib/fogdata/certs:/certs

  # UI CONTAINER
  mission-control-ui:
    image: ghcr.io/tiiuae/tii-mission-control-ui:3.0.0-rc.6
    depends_on:
      - offline-map-server
      - swarm-nats
      - management-nats
    restart: always
    environment:
      - CLIENT_ID={{device-id}}
      - FLEET_MANAGEMENT_HOSTNAME={{device-id}}
    ports:
        - 80:80

  # GPS SERVICE
  gps-service:
    image: ghcr.io/tiiuae/gps-service-laptop:0.1.16
    container_name: gps-service-laptop
    restart: on-failure
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - GPS_LAPTOP_DEVICE_ID_PATH=/certs/device_id.txt
      - GPS_LAPTOP_SERIAL_PORT=/dev/ttyACM0
      - GPS_LAPTOP_MANAGEMENT_NATS_SERVER=nats://{{ip-address}}:4222
      - GPS_LAPTOP_NATS_SERVER=nats://swarm-nats:4222
      - GPS_LAPTOP_SIMULATE=true
      - GPS_LAPTOP_LATITUDE=24.436311225969455
      - GPS_LAPTOP_LONGITUDE=54.61389614281878
      - GPS_LAPTOP_TLS_KEY_PATH=/certs/identity.key
      - GPS_LAPTOP_CLIENT_CERT_PATH=/certs/identity.crt
      - GPS_LAPTOP_TLS_ENABLED=true
    volumes:
      - /var/lib/fogdata/certs:/certs

  # MESH DATA BROKER
  mesh-data-broker:
    image: ghcr.io/tiiuae/mesh-data-broker:2.0.0
    restart: always
    depends_on:
      - swarm-nats
    environment:
      - DRONE_DEVICE_ID={{device-id}}
      # This is now hard coded and won't work
      - SOURCE_NATS_SERVER_URL=nats://192.168.42.1:4222
      - DESTINATION_NATS_SERVER_URL=nats://swarm-nats:4222

    # NTP server
  ntp:
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - "123:123/udp"
    environment:
      - LOG_LEVEL=0
      - NTP_SERVERS="127.127.1.1"
